AB#6467 Update "SpeakersGrid" to "FeaturedSpeakers" component on home…
Sitecore/Sitecore.Demo.Edge pull request #108
Opened 2021-09-09 11:02 UTC by adoprog

… page

2021-09-09 14:53 UTC, jflheureux requested changes

2021-09-10 06:51 UTC, adoprog commented on Website/src/items/content/EdgeWebsite/home/speakers/Page Components/Featured Speakers Section.yml
> +      Value: "Road-test the world's most trusted sports and fitness equipment – we'll be welcoming 2,000 brands at this year's PLAY! Summit."
I'll rollback my change to /speakers, but this means the text will not be added/updated.

2021-09-10 06:51 UTC, adoprog commented on Website/src/items/content/EdgeWebsite/home/speakers/Page Components/Featured Speakers Section.yml
> +      Value: Featured Speakers
I'll rollback my change to /speakers, but this means the text will not be added/updated.

2021-09-10 08:36 UTC, adoprog commented on Website/src/items/content/EdgeWebsite/home.yml
>            rname="SpeakersGrid"
Removed rname

2021-09-13 12:15 UTC, scottmulligan approved these changes
Looks good!

2021-09-14 08:22 UTC, merged