AB#6899 Vendor and sponsor connection with sessions and speakers
Sitecore/Sitecore.Demo.Edge pull request #250
Opened 2022-01-12 18:03 UTC by mintsitecore

2022-01-17 22:19 UTC, mintsitecore commented on Website/src/items/templates/edgewebsite/cmp entities/Speaker/Data/Sponsors.yml
> +  Value: CmpMultiList
yeah. leaving as many to many relations. some could have multiple. didnt want to limit.

2022-01-17 22:20 UTC, mintsitecore commented on Website/src/items/templates/edgewebsite/cmp entities/Speaker/Data/Vendors.yml
> +  Value: CmpMultiList
same as sponsor.

2022-01-25 20:00 UTC, jflheureux requested changes
Content review. I will do code review next

2022-01-25 20:48 UTC, jflheureux requested changes

2022-01-25 20:48 UTC, jflheureux commented on Website/src/rendering/src/stories/Sponsors/SponsorInformation.stories.tsx
> +import { SESSIONS } from '../../models/mock-sessions';
As the mock sessions are now only used in stories, it would be good to move them from the "models" folder to the root of the "stories" folder.

2022-01-26 21:54 UTC, jflheureux submitted a review, later dismissed
I have tested on the portal and found these last issues.

2022-01-26 21:54 UTC, jflheureux commented on Website/src/rendering/src/components/Vendors/VendorInformation.tsx
> +        <SessionList
SessionList seems to have a bug. The speaker links are not valid. Example: https://jel-pull0250-website.sitecoredemo.com/speakers/undefined

Could you please fix it in this PR as you used `showSpeakers={true}` ?

2022-01-26 21:54 UTC, jflheureux commented on Website/src/rendering/src/components/Vendors/VendorInformation.tsx
> +      <div className="column-title">There are no sessions available yet.</div>
When there is no sessions, the message and its style is different than when there is no speaker on a session (Example: /sessions/Lunch). Could you adjust the message and style to have a similar experience on all type of pages?

2022-01-26 21:54 UTC, jflheureux commented on Website/src/rendering/src/components/Sponsors/SponsorInformation.tsx
> +      <div className="column-title">There are no sessions available yet.</div>
When there is no sessions, the message and its style is different than when there is no speaker on a session (Example: /sessions/Lunch). Could you adjust the message and style to have a similar experience on all type of pages?

2022-01-27 20:24 UTC, jflheureux approved these changes

2022-01-27 20:37 UTC, merged