full image section background moved from css to sitecore item
Sitecore/Sitecore.Demo.Edge pull request #255
Opened 2022-01-26 00:04 UTC by mintsitecore

2022-01-26 02:11 UTC, mintsitecore commented
Once this change is reviewed and approved. 
step 2 update storybook
step 3 remove unused component (the map)

2022-02-11 14:26 UTC, jflheureux requested changes

2022-02-11 14:26 UTC, jflheureux commented on Website/src/items/templates/edgewebsite/PaymentProgress/__Standard Values.yml
> -        <r
`PaymentProgress` is a datasource template (not a page template). It should not have a layout and renderings. Could you please remove its layout and renderings? Thanks

2022-02-11 14:26 UTC, jflheureux commented on Website/src/rendering/src/components/PageContent/Promo.tsx
> +          {fields.callToActionLink.value.text && (
Please avoid mixing logic and markup inside the main JSX return. Please implement this condition with a const like the one in `FullImageSection.tsx`. Thanks

2022-02-11 14:26 UTC, jflheureux commented on Website/src/rendering/src/stories/PageContent/FullImageSection.stories.tsx
> +      value: 'section__full-image',
As with the serialized items, this class is not needed now. It can be an empty string.

2022-04-08 17:24 UTC, adoprog commented
Closing as not relevant at the moment.

2022-04-08 17:24 UTC, closed without merging