Feature/product detail page
Sitecore/Sitecore.Demo.Edge pull request #291
Opened 2022-03-09 16:53 UTC by mmoebeck

2022-03-15 21:10 UTC, jflheureux requested changes
As the code will change a lot by extracting the component(s), I will review the logic and rest of the code when the major changes are done.

2022-03-17 15:43 UTC, mmoebeck commented
I have pushed up changes.

2022-03-17 21:33 UTC, jflheureux requested changes
Thanks for the previous changes. The code architecture is better now!

This is a partial review. I am not done reviewing all logic. At least these comments will allow you to improve the code while I continue to review the rest of the code.

2022-03-17 21:33 UTC, jflheureux commented on Website/src/rendering/src/stories/Products/ProductDetailPage.stories.tsx
> +Default.args = {
Now that the cart PR with OrderCloud Redux store mock is merged in `feature/reflektion-poc`, could you please:
1. Merge `feature/reflektion-poc` into your branch.
2. Fix merge conflicts, if any,
3. Implement Storybook variants for the various states/possibilities of this component.

2022-03-17 21:33 UTC, jflheureux commented on Website/src/rendering/src/components/Products/ProductDetailPage.tsx
> +                {specs ? (
My previous comment about avoiding to mix markup and logic in the main return statement was not just for the productImage. I also mentioned to please extract constants for all the parts that are conditional in the pull request code.

This line is another example of a condition inside the main JSX of the component.

2022-03-17 21:33 UTC, jflheureux commented on Website/src/rendering/src/components/Products/ProductDetailPage.tsx
> +                {variants && !variantID ? (
This line is another example of a condition inside the main JSX of the component.

2022-03-17 21:33 UTC, jflheureux commented on Website/src/rendering/src/components/Products/ProductDetailPage.tsx
> +                        const specValue = specValues.find(
Would it be possible to move this lookup logic into a separate function outside the main JSX return to help keep the JSX as logic-free as possible? Thanks

2022-03-17 21:33 UTC, jflheureux commented on Website/src/rendering/src/components/Products/ProductQuantityInput.tsx
> +      {priceSchedule.RestrictedQuantity ? (
This line is another example of a condition inside the main JSX of the component.

2022-03-17 21:33 UTC, jflheureux commented on Website/src/rendering/src/components/Products/ProductSpecField.tsx
> +        {spec.OptionCount ? (
This line is another example of a condition inside the main JSX of the component.

2022-03-17 21:33 UTC, jflheureux commented on Website/src/rendering/src/components/Products/ProductDetailPage.tsx
> +const ProductDetailPage = (): JSX.Element => {
As the component is not really a page, maybe `ProductDetails` would be a name that better describes it. Could it please be renamed along with the Storybook file?

2022-03-17 21:33 UTC, jflheureux commented on Website/src/rendering/src/components/Products/ProductDetailPage.tsx
> +type specProps = {
`props` in react is a term to describe the input properties of a component. Here, I believe this type is not used as the input of a component. `Props` could be removed from its name.

2022-03-17 21:33 UTC, jflheureux commented on Website/src/rendering/src/components/Products/ProductDetailPage.tsx
> +type rfkResponse = {
Type and interface names should all start with a capital letter. This also applies to `specProps`.

2022-03-17 21:33 UTC, jflheureux commented on Website/src/rendering/src/components/Products/ProductDetailPage.tsx
> +type ProductProps = {
`props` in react is a term to describe the input properties of a component. Here, I believe this type is not used as the input of a component. `Props` could be removed from its name.

2022-03-17 21:33 UTC, jflheureux commented on Website/src/rendering/src/components/Products/ProductDetailPage.tsx
> +type rfkResponse = {
If this is not specific to the product details component, could it please be moved to `DiscoverService`?

2022-03-17 21:33 UTC, jflheureux commented on Website/src/rendering/src/components/Products/ProductDetailPage.tsx
> +type Widget = {
If this is not specific to the product details component, could it please be moved to `DiscoverService`?

2022-03-17 21:33 UTC, jflheureux commented on Website/src/rendering/src/components/Products/ProductDetailPage.tsx
> +type ProductProps = {
If this is not specific to the product details component, could it please be moved to `DiscoverService`?

2022-03-24 21:03 UTC, jflheureux approved these changes

2022-03-25 16:08 UTC, merged