#6115 Versioning and build
Sitecore/Sitecore.Demo.Edge pull request #3
Opened 2021-05-27 17:57 UTC by adoprog

2021-05-28 19:00 UTC, jflheureux requested changes
Great work. Found a couple of issues and multiple improvement ideas.

2021-05-31 13:15 UTC, adoprog commented on init-ci.ps1
> +  [string]$SitecoreVersion = "10.1.0"
Updated .env to use 10.1.0

2021-05-31 13:26 UTC, jflheureux commented on docker-compose.override.yml
> +        PARENT_IMAGE: scr.sitecore.com/sxp/sitecore-xm1-mssql-init:10.1-${WINDOWSSERVERCORE_VERSION}
`scr.sitecore.com/` should be replaced by `${SITECORE_DOCKER_REGISTRY}` too

2021-05-31 13:31 UTC, jflheureux commented on init-ci.ps1
> +  [string]$SitecoreVersion = "10.1.0"
I think this has not been committed.

2021-05-31 13:33 UTC, adoprog commented on docker-compose.override.yml
> +        PARENT_IMAGE: scr.sitecore.com/sxp/sitecore-xm1-mssql-init:10.1-${WINDOWSSERVERCORE_VERSION}
Done.

2021-05-31 13:33 UTC, adoprog commented on init-ci.ps1
> +  [string]$SitecoreVersion = "10.1.0"
Right, thanks. pushed it now.

2021-05-31 13:39 UTC, jflheureux approved these changes

2021-05-31 13:42 UTC, merged