Using version 0.2.0 of scd-sdk
Sitecore/Sitecore.Demo.Edge pull request #326
Opened 2022-04-15 22:01 UTC by maxwmaher

1) Preview Search and Full Page Search are using the 0.2.0 version of the scd-sdk from the private registry.
2) Also includes fixes for user stories 7316, 7318, 7319, & 7320

2022-04-18 21:06 UTC, jflheureux requested changes
Quick review. I have not reviewed the component files yet.

2022-04-18 21:06 UTC, jflheureux commented on Website/src/rendering/src/services/DiscoverService.tsx
> -        window.RFK.setWidget('ps_trending_categories', {
Did you forget to setup this widget in the new implementation?

2022-04-18 21:06 UTC, jflheureux commented on Website/src/rendering/src/services/DiscoverService.tsx
> -        window.RFK.setWidget('rfkid_11', {
Did you forget to setup this widget in the new implementation?

2022-04-18 21:06 UTC, jflheureux commented on Website/src/rendering/.npmrc
> +@sitecore-discover:registry=https://sitecore.myget.org/F/sc-npm-packages/npm/
Removing the file will break the CI build. We will have to find another way to add this registry to the CI build

2022-04-19 15:05 UTC, maxwmaher commented on Website/src/rendering/tsconfig.json
> +    "incremental": true
I can't, it looks like this file automatically got adjusted during my first commit (557f95 - Connection to scd-sdk). Do you know what processes affect the change of values in this file?

2022-04-22 01:23 UTC, jflheureux approved these changes

2022-04-22 01:54 UTC, merged