AB#6702 Pre-fill form fields
Sitecore/Sitecore.Demo.Edge pull request #440
Opened 2022-07-27 08:07 UTC by NellyKostadinova

2022-08-03 16:11 UTC, chpa7 requested changes

2022-08-03 16:11 UTC, chpa7 commented on Website/src/rendering/src/components/Forms/AttendeeForm.tsx
> +    const getUserData = async () => {
Would it be possible to extract this function into a helper file, given that it is used in all three forms?

2022-08-04 10:04 UTC, NellyKostadinova commented on Website/src/rendering/src/services/BoxeverService.tsx
>    return `${data.firstName} ${data.lastName}`;
Currently yes, but what if at some point there is a form which requires just one of the names?

2022-08-05 18:07 UTC, chpa7 commented on Website/src/rendering/src/services/BoxeverService.tsx
>    return `${data.firstName} ${data.lastName}`;
Doesn't seem too likely to be honest, but I guess it also doesn't hurt to be future-proof.

2022-08-05 18:08 UTC, chpa7 approved these changes

2022-08-08 07:29 UTC, merged