AB#7018 sitecore send content json added to demo folder
Sitecore/Sitecore.Demo.Edge pull request #448
Opened 2022-08-03 18:07 UTC by mintsitecore

2022-08-03 19:52 UTC, jflheureux requested changes
Please review all the serialized automations, campaigns, landing pages, and mailing lists. Identify those that are really used. Delete the ones that are unused.

2022-08-03 19:52 UTC, jflheureux commented on demo/send/mailingLists/7dc7a9bd-0a14-427f-894a-66d8f7a938db.json
> +{"Campaign":null,"SendToDetails":null,"Content":null,"OptIn":0,"SegmentsCount":0,"LastDayChanges":0,"ActiveSubscribers":5,"MailingList":{"Id":"7dc7a9bd-0a14-427f-894a-66d8f7a938db","MailingListCode":
is this "first mailing list" really used by the solution and must be serialized here? Should it be renamed to something more meaningful if it is being used?

2022-08-03 19:52 UTC, jflheureux commented on demo/send/mailingLists/3c869606-e1d4-4d37-9267-5e38bc6efeb8.json
> +{"Campaign":null,"SendToDetails":null,"Content":null,"OptIn":0,"SegmentsCount":0,"LastDayChanges":0,"ActiveSubscribers":2,"MailingList":{"Id":"3c869606-e1d4-4d37-9267-5e38bc6efeb8","MailingListCode":
is this "Generated for Email Activity" really used by the solution and must be serialized here? Should it be renamed to something more meaningful if it is being used?

2022-08-03 19:52 UTC, jflheureux commented on demo/send/mailingLists/27cda576-4a60-4621-b515-8489b396a300.json
> +{"Campaign":null,"SendToDetails":null,"Content":null,"OptIn":0,"SegmentsCount":0,"LastDayChanges":0,"ActiveSubscribers":2,"MailingList":{"Id":"27cda576-4a60-4621-b515-8489b396a300","MailingListCode":
is this "Subscribers from https://adotest-cm.sitecoredemo.com/" really used by the solution and must be serialized here? Should it be renamed to something more meaningful if it is being used?

2022-08-03 19:52 UTC, jflheureux commented on demo/send/landingPages/9ed4f663-8687-4df2-8f35-a201231312b4.json
> +{"Campaign":null,"SendToDetails":null,"Content":null,"OptIn":0,"SegmentsCount":0,"LastDayChanges":0,"ActiveSubscribers":0,"MailingList":null,"Entity":{"ConversionPercentage":0,"CreatedBy":"129.222.16
is this "jf-test" really used by the solution and must be serialized here? Should it be renamed to something more meaningful if it is being used?

2022-08-03 19:52 UTC, jflheureux commented on demo/send/campaigns/4ff6e5fe-3560-40c0-abf0-7834ed05de3d.json
> +{"Campaign":{"UserId":"7dc7a9bd-0a14-427f-894a-66d8f7a938db","CampaignId":"4ff6e5fe-3560-40c0-abf0-7834ed05de3d","CreatedOn":"/Date(1658417056903-0000)/","UpdatedOn":"/Date(1658851281737-0000)/","Cam
is this "Generated for Email Activity" really used by the solution and must be serialized here? Should it be renamed to something more meaningful if it is being used?

2023-02-17 19:38 UTC, adoprog commented
We've added this content (and more) to portal provisioning.

2023-02-17 19:38 UTC, closed without merging